[theme]
primaryColor = "#0875E1"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F1F1F"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
